version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: joyhouse
      POSTGRES_USER: joyhouse
      POSTGRES_PASSWORD: joyhouse123
      # 性能优化参数
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # 时区设置
      TZ: "Asia/Shanghai"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_preload_libraries=pgvector
      -c max_connections=1000
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joyhouse -d joyhouse"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  postgres_data: 